# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\"#\n\rLookupRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\"^\n\x0eLookupResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t\"C\n\x0cTradeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0fnumber_of_items\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x1d\n\rTradeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x32\x63\n\x0e\x43\x61talogService\x12)\n\x06Lookup\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\x12&\n\x05Trade\x12\r.TradeRequest\x1a\x0e.TradeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=17
  _globals['_LOOKUPREQUEST']._serialized_end=52
  _globals['_LOOKUPRESPONSE']._serialized_start=54
  _globals['_LOOKUPRESPONSE']._serialized_end=148
  _globals['_TRADEREQUEST']._serialized_start=150
  _globals['_TRADEREQUEST']._serialized_end=217
  _globals['_TRADERESPONSE']._serialized_start=219
  _globals['_TRADERESPONSE']._serialized_end=248
  _globals['_CATALOGSERVICE']._serialized_start=250
  _globals['_CATALOGSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
